//  Constants for React Redux actions and reducers

// Constants for Employees
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR' 

export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS'
export const FETCH_EMPLOYEE_ERROR = 'FETCH_EMPLOYEE_ERROR'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR'
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS'
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR'

export const CLEAR_EMPLOYEES_MESSAGE = 'CLEAR_EMPLOYEES_MESSAGE'

// Constants for Absences
export const ADD_ABSENCE_SUCCESS = 'ADD_ABSENCE_SUCCESS'
export const ADD_ABSENCE_ERROR = 'ADD_ABSENCE_ERROR'
export const UPDATE_ABSENCE_SUCCESS = 'UPDATE_ABSENCE_SUCCESS'
export const UPDATE_ABSENCE_ERROR = 'UPDATE_ABSENCE_ERROR'
export const DELETE_ABSENCE_SUCCESS = 'DELETE_ABSENCE_SUCCESS'
export const DELETE_ABSENCE_ERROR = 'DELETE_ABSENCE_ERROR'

export const CLEAR_ABSENCE_MESSAGE = 'CLEAR_ABSENCE_MESSAGE'

// Constants for Jobtitles
export const FETCH_JOBTITLES_SUCCESS = 'FETCH_JOBTITLES_SUCCESS'
export const FETCH_JOBTITLES_ERROR = 'FETCH_JOBTITLES_ERROR'
export const ADD_JOBTITLE_SUCCESS = 'ADD_JOBTITLE_SUCCESS'
export const ADD_JOBTITLE_ERROR = 'ADD_JOBTITLE_ERROR'
export const UPDATE_JOBTITLE_SUCCESS = 'UPDATE_JOBTITLE_SUCCESS'
export const UPDATE_JOBTITLE_ERROR = 'UPDATE_JOBTITLE_ERROR'
export const DELETE_JOBTITLE_SUCCESS = 'DELETE_JOBTITLE_SUCCESS'
export const DELETE_JOBTITLE_ERROR = 'DELETE_JOBTITLE_ERROR'

export const CLEAR_JOBTITLE_MESSAGE = 'CLEAR_JOBTITLE_MESSAGE'

// Constants for Schedules
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS'
export const FETCH_SCHEDULES_ERROR = 'FETCH_SCHEDULES_ERROR'
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS'
export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR'
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS'
export const ADD_SCHEDULE_ERROR = 'ADD_SCHEDULE_ERROR'
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS'
export const UPDATE_SCHEDULE_ERROR = 'UPDATE_SCHEDULE_ERROR'
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS'
export const DELETE_SCHEDULE_ERROR = 'DELETE_SCHEDULE_ERROR'

export const CLEAR_SCHEDULES_MESSAGE = 'CLEAR_SCHEDULES_MESSAGE'


// Constants for Authorization
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const AUTH_SHOW_LOADING = 'AUTH_SHOW_LOADING'
export const AUTH_HIDE_LOADING = 'AUTH_HIDE_LOADING'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

// Constats for Loading
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'